import type { ExerciseSeed } from "../types.js";

export default [
  {
    title: "Basic text styling",
    brief: "Style the text of a page: the body font, the main heading colour and the paragraph size.",
    steps: [
      "body: set font-family (any font stack)",
      "h1: set color (any colour)",
      "p: set font-size to a value in px or rem",
      "p: set line-height (for example 1.5)",
    ],
    level: "basic",
    editor: "css",
    starter: `body {\n\n}\n\nh1 {\n\n}\n\np {\n\n}\n`,
    solution: `body {\n  font-family: Arial, Helvetica, sans-serif;\n}\n\nh1 {\n  color: #1e3a8a;\n}\n\np {\n  font-size: 1.1rem;\n  line-height: 1.5;\n}\n`,
    check: {
      rules: [
        { css: "body", prop: "font-family", message: "body sets a font-family" },
        { css: "h1", prop: "color", message: "h1 sets a color" },
        { css: "p", prop: "font-size", value: String.raw`^\d*\.?\d+(px|rem)$`, message: "p sets font-size in px or rem" },
        { css: "p", prop: "line-height", message: "p sets a line-height" },
      ],
    },
  },
  {
    title: "Box model card",
    brief: "Turn a .card element into a boxed card using padding, a border, rounded corners and margin.",
    steps: [
      ".card: padding of 16px or more (any unit)",
      ".card: a solid border (e.g. 1px solid #ccc)",
      ".card: border-radius (e.g. 8px)",
      ".card: margin (e.g. 20px auto) and box-sizing: border-box",
    ],
    level: "basic",
    editor: "css",
    starter: `.card {\n  /* padding, border, radius, margin */\n}\n`,
    solution: `.card {\n  padding: 20px;\n  border: 1px solid #ccc;\n  border-radius: 8px;\n  margin: 20px auto;\n  box-sizing: border-box;\n}\n`,
    check: {
      rules: [
        { css: ".card", prop: "padding", message: ".card sets padding" },
        { css: ".card", prop: "border", value: "solid", message: ".card has a solid border" },
        { css: ".card", prop: "border-radius", message: ".card has rounded corners (border-radius)" },
        { css: ".card", prop: "margin", message: ".card sets margin" },
        { css: ".card", prop: "box-sizing", value: "^border-box$", message: ".card uses box-sizing: border-box" },
      ],
    },
  },
  {
    title: "Button with hover state",
    brief: "Style a .btn class as a coloured button that changes colour when the mouse is over it.",
    steps: [
      ".btn: background-color, color and padding",
      ".btn: border: none and cursor: pointer",
      ".btn:hover: a different background-color",
    ],
    level: "basic",
    editor: "css",
    starter: `.btn {\n\n}\n\n/* Add a hover rule */\n`,
    solution: `.btn {\n  background-color: #2563eb;\n  color: white;\n  padding: 10px 18px;\n  border: none;\n  cursor: pointer;\n}\n\n.btn:hover {\n  background-color: #1d4ed8;\n}\n`,
    check: {
      rules: [
        { css: ".btn", prop: "background-color", message: ".btn sets a background-color" },
        { css: ".btn", prop: "color", message: ".btn sets a text color" },
        { css: ".btn", prop: "padding", message: ".btn sets padding" },
        { css: ".btn", prop: "border", value: "^(none|0)$", message: ".btn has border: none" },
        { css: ".btn", prop: "cursor", value: "^pointer$", message: ".btn has cursor: pointer" },
        { css: ".btn:hover", prop: "background-color", message: ".btn:hover changes the background-color" },
      ],
    },
  },
  {
    title: "Center with flexbox",
    brief: "Center a box horizontally and vertically inside a full-height .center container using flexbox.",
    steps: [
      ".center: display: flex",
      ".center: justify-content: center",
      ".center: align-items: center",
      ".center: min-height: 100vh (or height: 100vh)",
    ],
    level: "basic",
    editor: "css",
    starter: `.center {\n  text-align: center;\n}\n`,
    solution: `.center {\n  display: flex;\n  justify-content: center;\n  align-items: center;\n  min-height: 100vh;\n}\n`,
    check: {
      rules: [
        { css: ".center", prop: "display", value: "^flex$", message: ".center uses display: flex" },
        { css: ".center", prop: "justify-content", value: "^center$", message: ".center has justify-content: center" },
        { css: ".center", prop: "align-items", value: "^center$", message: ".center has align-items: center" },
        { match: String.raw`\.center\s*\{[^}]*(min-)?height\s*:\s*100vh`, message: ".center is at least 100vh tall" },
      ],
    },
  },
  {
    title: "Three-column grid",
    brief: "Lay out the items of a .grid container in three equal columns with a gap using CSS Grid.",
    steps: [
      ".grid: display: grid",
      ".grid: grid-template-columns with three equal columns (repeat(3, 1fr) or 1fr 1fr 1fr)",
      ".grid: gap (e.g. 16px)",
      ".grid .item: padding and a background-color",
    ],
    level: "intermediate",
    editor: "css",
    starter: `.grid {\n\n}\n\n.grid .item {\n\n}\n`,
    solution: `.grid {\n  display: grid;\n  grid-template-columns: repeat(3, 1fr);\n  gap: 16px;\n}\n\n.grid .item {\n  padding: 12px;\n  background-color: #f1f5f9;\n}\n`,
    check: {
      rules: [
        { css: ".grid", prop: "display", value: "^grid$", message: ".grid uses display: grid" },
        { css: ".grid", prop: "grid-template-columns", value: String.raw`^(repeat\(\s*3\s*,\s*1fr\s*\)|1fr\s+1fr\s+1fr)$`, message: ".grid has three equal columns" },
        { css: ".grid", prop: "gap", message: ".grid sets a gap" },
        { css: ".grid .item", prop: "padding", message: ".grid .item sets padding" },
        { css: ".grid .item", prop: "background-color", message: ".grid .item sets a background-color" },
      ],
    },
  },
  {
    title: "Sticky header",
    brief: "Make the page header stay at the top while the page scrolls, above the other content.",
    steps: [
      "header: position: sticky",
      "header: top: 0",
      "header: a z-index (e.g. 10)",
      "header: a background-color and a box-shadow",
    ],
    level: "intermediate",
    editor: "css",
    starter: `header {\n  padding: 12px 20px;\n}\n`,
    solution: `header {\n  padding: 12px 20px;\n  position: sticky;\n  top: 0;\n  z-index: 10;\n  background-color: #fff;\n  box-shadow: 0 2px 4px rgba(0, 0, 0, 0.1);\n}\n`,
    check: {
      rules: [
        { css: "header", prop: "position", value: "^sticky$", message: "header uses position: sticky" },
        { css: "header", prop: "top", value: "^0(px)?$", message: "header has top: 0" },
        { css: "header", prop: "z-index", message: "header sets a z-index" },
        { css: "header", prop: "background-color", message: "header sets a background-color" },
        { css: "header", prop: "box-shadow", message: "header has a box-shadow" },
      ],
    },
  },
  {
    title: "Theme with CSS variables",
    brief: "Define brand colours once as custom properties on :root and use them with var() in other rules.",
    steps: [
      ":root: define --brand and --bg custom properties",
      "body: background-color: var(--bg)",
      ".title: color: var(--brand)",
      ".btn: background-color: var(--brand)",
    ],
    level: "intermediate",
    editor: "css",
    starter: `:root {\n\n}\n\nbody {\n  background-color: #f8fafc;\n}\n\n.title {\n  color: #7c3aed;\n}\n\n.btn {\n  background-color: #7c3aed;\n}\n`,
    solution: `:root {\n  --brand: #7c3aed;\n  --bg: #f8fafc;\n}\n\nbody {\n  background-color: var(--bg);\n}\n\n.title {\n  color: var(--brand);\n}\n\n.btn {\n  background-color: var(--brand);\n}\n`,
    check: {
      rules: [
        { css: ":root", prop: "--brand", message: ":root defines --brand" },
        { css: ":root", prop: "--bg", message: ":root defines --bg" },
        { css: "body", prop: "background-color", value: String.raw`var\(\s*--bg\s*\)`, message: "body uses var(--bg)" },
        { css: ".title", prop: "color", value: String.raw`var\(\s*--brand\s*\)`, message: ".title uses var(--brand)" },
        { css: ".btn", prop: "background-color", value: String.raw`var\(\s*--brand\s*\)`, message: ".btn uses var(--brand)" },
      ],
    },
  },
  {
    title: "Mobile-first media query",
    brief: "Stack the .menu links vertically on phones and show them in a row on screens 768px and wider.",
    steps: [
      ".menu: display: flex and flex-direction: column (the phone layout)",
      "Add @media (min-width: 768px)",
      "Inside it, .menu: flex-direction: row",
    ],
    level: "intermediate",
    editor: "css",
    starter: `.menu {\n  display: flex;\n}\n\n/* Add a media query for wider screens */\n`,
    solution: `.menu {\n  display: flex;\n  flex-direction: column;\n  gap: 8px;\n}\n\n@media (min-width: 768px) {\n  .menu {\n    flex-direction: row;\n  }\n}\n`,
    check: {
      rules: [
        { css: ".menu", prop: "display", value: "^flex$", message: ".menu uses display: flex" },
        { css: ".menu", prop: "flex-direction", value: "^column$", message: ".menu stacks as a column on phones" },
        { cssAt: "media", prelude: String.raw`min-width\s*:\s*768px`, message: "A @media (min-width: 768px) query" },
        { css: ".menu", prop: "flex-direction", value: "^row$", inside: String.raw`min-width\s*:\s*768px`, message: "Inside the media query, .menu uses flex-direction: row" },
      ],
    },
  },
  {
    title: "Fade-in keyframes",
    brief: "Write a fadeIn keyframes animation that goes from invisible to visible, and apply it to .box.",
    steps: [
      "@keyframes fadeIn with a from block (opacity: 0) and a to block (opacity: 1)",
      "from also sets transform: translateY(20px); to sets transform: translateY(0)",
      ".box: animation using fadeIn with a duration (e.g. animation: fadeIn 0.6s ease-out)",
    ],
    level: "advanced",
    editor: "css",
    starter: `.box {\n  padding: 20px;\n}\n\n/* Define @keyframes fadeIn and use it on .box */\n`,
    solution: `@keyframes fadeIn {\n  from {\n    opacity: 0;\n    transform: translateY(20px);\n  }\n  to {\n    opacity: 1;\n    transform: translateY(0);\n  }\n}\n\n.box {\n  padding: 20px;\n  animation: fadeIn 0.6s ease-out;\n}\n`,
    check: {
      rules: [
        { cssAt: "keyframes", prelude: "^fadeIn$", message: "A @keyframes fadeIn rule" },
        { css: "from", prop: "opacity", value: "^0$", message: "The animation starts at opacity: 0" },
        { css: "to", prop: "opacity", value: "^1$", message: "The animation ends at opacity: 1" },
        { css: "from", prop: "transform", value: "translateY", message: "from moves the box with translateY" },
        { css: ".box", prop: "animation", value: String.raw`\bfadeIn\b.*\d(ms|s)|\d(ms|s).*\bfadeIn\b`, message: ".box uses the fadeIn animation with a duration" },
      ],
    },
  },
  {
    title: "Auto-fit image gallery",
    brief: "Build a gallery grid that fits as many 200px-wide columns as the screen allows, with images that fill their cells.",
    steps: [
      ".gallery: display: grid and a gap",
      ".gallery: grid-template-columns: repeat(auto-fit, minmax(200px, 1fr))",
      ".gallery img: width: 100%, height (e.g. 180px) and object-fit: cover",
      "Add @media (max-width: 480px) that sets .gallery gap to a smaller value",
    ],
    level: "advanced",
    editor: "css",
    starter: `.gallery {\n  display: grid;\n}\n\n.gallery img {\n\n}\n`,
    solution: `.gallery {\n  display: grid;\n  grid-template-columns: repeat(auto-fit, minmax(200px, 1fr));\n  gap: 16px;\n}\n\n.gallery img {\n  width: 100%;\n  height: 180px;\n  object-fit: cover;\n}\n\n@media (max-width: 480px) {\n  .gallery {\n    gap: 8px;\n  }\n}\n`,
    check: {
      rules: [
        { css: ".gallery", prop: "display", value: "^grid$", message: ".gallery uses display: grid" },
        { css: ".gallery", prop: "grid-template-columns", value: String.raw`repeat\(\s*auto-(fit|fill)\s*,\s*minmax\(\s*200px\s*,\s*1fr\s*\)\s*\)`, message: ".gallery uses repeat(auto-fit, minmax(200px, 1fr))" },
        { css: ".gallery", prop: "gap", message: ".gallery sets a gap" },
        { css: ".gallery img", prop: "width", value: "^100%$", message: "Gallery images are 100% wide" },
        { css: ".gallery img", prop: "object-fit", value: "^cover$", message: "Gallery images use object-fit: cover" },
        { cssAt: "media", prelude: String.raw`max-width\s*:\s*480px`, message: "A @media (max-width: 480px) query" },
      ],
    },
  },
] satisfies ExerciseSeed[];
